/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Telas;

import Controller.Aluno;
import Controller.Perfil;
import Model.AlunoDAO;
import Model.PerfilDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruan Fagundes
 */
public class SubmeterNotaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form AlunoP
     */
    public SubmeterNotaProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
     /*-------------------------------------------
     *              MEUS METODOS 
     *------------------------------------------*/
    
    //INICIANTE
    public void attTableI(){
        AlunoDAO aDAO = new AlunoDAO();
        PerfilDAO p = new PerfilDAO();
        try{
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int quant = jTable1.getRowCount();            
            for (int i=0;i<quant;i++){
                dtm.removeRow(0);
            }
            if (aDAO.buscarAluno()!= null){
                for(Aluno lista : aDAO.buscarAluno()){ 
                    Perfil li = p.buscarPerfil(lista.getId());
                    if(li.getNivel().equals("Iniciante")){
                        dtm.addRow(new Object[]{li.getId(),lista.getAluno(),li.getNota1(),li.getNota2(),li.getNotaFinal()});
                    }
                    
                }
            }              
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //BASICO
    public void attTableB(){
        AlunoDAO aDAO = new AlunoDAO();
        PerfilDAO p = new PerfilDAO();
        try{
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            int quant = jTable2.getRowCount();            
            for (int i=0;i<quant;i++){
                dtm.removeRow(0);
            }
            if (aDAO.buscarAluno()!= null){
                for(Aluno lista : aDAO.buscarAluno()){ 
                    Perfil li = p.buscarPerfil(lista.getId());
                    if(li.getNivel().equals("Basico")){
                        dtm.addRow(new Object[]{li.getId(),lista.getAluno(),li.getNota1(),li.getNota2(),li.getNotaFinal()});
                    }
                }
            }              
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //INTERMEDIARIO
    public void attTableIT(){
        AlunoDAO aDAO = new AlunoDAO();
        PerfilDAO p = new PerfilDAO();
        try{
            DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
            int quant = jTable3.getRowCount();            
            for (int i=0;i<quant;i++){
                dtm.removeRow(0);
            }
            if (aDAO.buscarAluno()!= null){
                for(Aluno lista : aDAO.buscarAluno()){ 
                    Perfil li = p.buscarPerfil(lista.getId());
                    if(li.getNivel().equals("Intermediario")){
                        dtm.addRow(new Object[]{li.getId(),lista.getAluno(),li.getNota1(),li.getNota2(),li.getNotaFinal()});
                    }
                }
            }              
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //AVANÇADO
    public void attTableA(){
        AlunoDAO aDAO = new AlunoDAO();
        PerfilDAO p = new PerfilDAO();
        try{
            DefaultTableModel dtm = (DefaultTableModel) jTable4.getModel();
            int quant = jTable4.getRowCount();            
            for (int i=0;i<quant;i++){
                dtm.removeRow(0);
            }
            if (aDAO.buscarAluno()!= null){
                for(Aluno lista : aDAO.buscarAluno()){ 
                    Perfil li = p.buscarPerfil(lista.getId());
                    if(li.getNivel().equals("Avançado")){
                        dtm.addRow(new Object[]{li.getId(),lista.getAluno(),li.getNota1(),li.getNota2(),li.getNotaFinal()});
                    }
                    
                }
            }              
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //EXPERIENTE
    public void attTableE(){
        AlunoDAO aDAO = new AlunoDAO();
        PerfilDAO p = new PerfilDAO();
        try{
            DefaultTableModel dtm = (DefaultTableModel) jTable5.getModel();
            int quant = jTable5.getRowCount();            
            for (int i=0;i<quant;i++){
                dtm.removeRow(0);
            }
            if (aDAO.buscarAluno()!= null){
                for(Aluno lista : aDAO.buscarAluno()){ 
                    Perfil li = p.buscarPerfil(lista.getId());
                    if(li.getNivel().equals("Experiente")){
                        dtm.addRow(new Object[]{li.getId(),lista.getAluno(),li.getNota1(),li.getNota2(),li.getNotaFinal()});
                    }
                    
                }
            }              
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    //FLUENTE
    public void attTableF(){
        AlunoDAO aDAO = new AlunoDAO();
        PerfilDAO p = new PerfilDAO();
        try{
            DefaultTableModel dtm = (DefaultTableModel) jTable6.getModel();
            int quant = jTable6.getRowCount();            
            for (int i=0;i<quant;i++){
                dtm.removeRow(0);
            }
            if (aDAO.buscarAluno()!= null){
                for(Aluno lista : aDAO.buscarAluno()){ 
                    Perfil li = p.buscarPerfil(lista.getId());
                    if(li.getNivel().equals("Fluente")){
                        dtm.addRow(new Object[]{li.getId(),lista.getAluno(),li.getNota1(),li.getNota2(),li.getNotaFinal()});
                    }                    
                }
            }              
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Basico");
        jPanel1.add(jButton1);

        jButton2.setText("Aprendiz");
        jPanel1.add(jButton2);

        jButton3.setText("Intermediário");
        jPanel1.add(jButton3);

        jButton5.setText("Avançado");
        jPanel1.add(jButton5);

        jButton4.setText("Fluente");
        jPanel1.add(jButton4);

        jButton6.setText("Experiente");
        jPanel1.add(jButton6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("© All rights reserved 2019");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Desevolvedores : Pedro Neto e Ruan Rita  ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel44.setBackground(new java.awt.Color(214, 217, 223));
        jPanel44.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jButton22.setBackground(new java.awt.Color(51, 51, 51));
        jButton22.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Home");
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton22MouseExited(evt);
            }
        });
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton22);

        jButton23.setBackground(new java.awt.Color(51, 51, 51));
        jButton23.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Submeter Nota");
        jButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton23MouseExited(evt);
            }
        });
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton23);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel8);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel4);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel2);

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Desconectar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jTable1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Aluno", "Nota1", "Nota2", "NotaFinal"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Iniciante", jPanel3);

        jTable2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Aluno", "Nota1", "Nota2", "NotaFinal"
            }
        ));
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Basico", jPanel9);

        jTable3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Aluno", "Nota1", "Nota2", "NotaFinal"
            }
        ));
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable3MouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);
        jTable3.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Intermediario", jPanel10);

        jTable4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Aluno", "Nota1", "Nota2", "NotaFinal"
            }
        ));
        jTable4.getTableHeader().setReorderingAllowed(false);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable4MouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);
        jTable4.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Avançado", jPanel11);

        jTable5.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Aluno", "Nota1", "Nota2", "NotaFinal"
            }
        ));
        jTable5.getTableHeader().setReorderingAllowed(false);
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable5MouseEntered(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);
        jTable5.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Experiente", jPanel12);

        jTable6.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Aluno", "Nota1", "Nota2", "NotaFinal"
            }
        ));
        jTable6.getTableHeader().setReorderingAllowed(false);
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable6MouseEntered(evt);
            }
        });
        jScrollPane6.setViewportView(jTable6);
        jTable6.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1271, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Fluente", jPanel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22MouseEntered

    private void jButton22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22MouseExited

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        MenuPrincipalProfessor MPF = new MenuPrincipalProfessor();
        MPF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23MouseEntered

    private void jButton23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton23MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23MouseExited

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        SubmeterNotaProfessor ALP = new SubmeterNotaProfessor();
        ALP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        attTableI();
        attTableB();
        attTableIT();
        attTableA();
        attTableE();
        attTableF();
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        PerfilDAO pdao = new PerfilDAO();
        int quant = jTable1.getRowCount();
        int ra = 0;
        Double nota1 = 0.0;
        Double nota2 = 0.0;
        Double notafinal = 0.0;
        for(int i =0 ; i<quant; i++){
            ra = Integer.parseInt(String.valueOf(dtm.getValueAt(i, 0)));
            nota1 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 2)));
            nota2 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 3)));
            notafinal = (nota1 + nota2) / 2;
            dtm.setValueAt(notafinal, i, 4);
            pdao.alterarNota(ra, nota1, nota2, notafinal);
        }
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        PerfilDAO pdao = new PerfilDAO();
        int quant = jTable2.getRowCount();
        int ra = 0;
        Double nota1 = 0.0;
        Double nota2 = 0.0;
        Double notafinal = 0.0;
        for(int i =0 ; i<quant; i++){
            ra = Integer.parseInt(String.valueOf(dtm.getValueAt(i, 0)));
            nota1 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 2)));
            nota2 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 3)));
            notafinal = (nota1 + nota2) / 2;
            dtm.setValueAt(notafinal, i, 4);
            pdao.alterarNota(ra, nota1, nota2, notafinal);
        }
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseEntered
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel) jTable3.getModel();
        PerfilDAO pdao = new PerfilDAO();
        int quant = jTable3.getRowCount();
        int ra = 0;
        Double nota1 = 0.0;
        Double nota2 = 0.0;
        Double notafinal = 0.0;
        for(int i =0 ; i<quant; i++){
            ra = Integer.parseInt(String.valueOf(dtm.getValueAt(i, 0)));
            nota1 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 2)));
            nota2 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 3)));
            notafinal = (nota1 + nota2) / 2;
            dtm.setValueAt(notafinal, i, 4);
            pdao.alterarNota(ra, nota1, nota2, notafinal);
        }
    }//GEN-LAST:event_jTable3MouseEntered

    private void jTable4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseEntered
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable4.getModel();
        PerfilDAO pdao = new PerfilDAO();
        int quant = jTable4.getRowCount();
        int ra = 0;
        Double nota1 = 0.0;
        Double nota2 = 0.0;
        Double notafinal = 0.0;
        for(int i =0 ; i<quant; i++){
            ra = Integer.parseInt(String.valueOf(dtm.getValueAt(i, 0)));
            nota1 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 2)));
            nota2 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 3)));
            notafinal = (nota1 + nota2) / 2;
            dtm.setValueAt(notafinal, i, 4);
            pdao.alterarNota(ra, nota1, nota2, notafinal);
        }
    }//GEN-LAST:event_jTable4MouseEntered

    private void jTable5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseEntered
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable5.getModel();
        PerfilDAO pdao = new PerfilDAO();
        int quant = jTable5.getRowCount();
        int ra = 0;
        Double nota1 = 0.0;
        Double nota2 = 0.0;
        Double notafinal = 0.0;
        for(int i =0 ; i<quant; i++){
            ra = Integer.parseInt(String.valueOf(dtm.getValueAt(i, 0)));
            nota1 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 2)));
            nota2 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 3)));
            notafinal = (nota1 + nota2) / 2;
            dtm.setValueAt(notafinal, i, 4);
            pdao.alterarNota(ra, nota1, nota2, notafinal);
        }
    }//GEN-LAST:event_jTable5MouseEntered

    private void jTable6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseEntered
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable6.getModel();
        PerfilDAO pdao = new PerfilDAO();
        int quant = jTable6.getRowCount();
        int ra = 0;
        Double nota1 = 0.0;
        Double nota2 = 0.0;
        Double notafinal = 0.0;
        for(int i =0 ; i<quant; i++){
            ra = Integer.parseInt(String.valueOf(dtm.getValueAt(i, 0)));
            nota1 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 2)));
            nota2 = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 3)));
            notafinal = (nota1 + nota2) / 2;
            dtm.setValueAt(notafinal, i, 4);
            pdao.alterarNota(ra, nota1, nota2, notafinal);
        }
    }//GEN-LAST:event_jTable6MouseEntered

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    // End of variables declaration//GEN-END:variables
}
