/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Telas;

/**
 *
 * @author Ruan Fagundes
 */
public class Turma extends javax.swing.JFrame {

    /**
     * Creates new form Turma
     */
    public Turma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable12 = new javax.swing.JTable();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTable17 = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable18 = new javax.swing.JTable();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable19 = new javax.swing.JTable();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable20 = new javax.swing.JTable();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable21 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(10, 10));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel1.setText("Turmas ");

        jTable12.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jTable12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", null, null, null, null},
                {"02", null, null, null, null},
                {"03", null, null, null, null},
                {"04", null, null, null, null},
                {"05", null, null, null, null},
                {"06", null, null, null, null},
                {"07", null, null, null, null},
                {"08", null, null, null, null},
                {"09", null, null, null, null},
                {"10", null, null, null, null},
                {"11", null, null, null, null},
                {"12", null, null, null, null},
                {"13", null, null, null, null},
                {"14", null, null, null, null},
                {"15", null, null, null, null},
                {"16", null, null, null, null},
                {"17", null, null, null, null},
                {"18", null, null, null, null},
                {"19", null, null, null, null},
                {"20", null, null, null, null}
            },
            new String [] {
                "Nº ", "Aluno", "E-mail", "Cell", "Nota"
            }
        ));
        jTable12.setGridColor(new java.awt.Color(51, 51, 51));
        jTable12.setRowHeight(19);
        jScrollPane12.setViewportView(jTable12);

        jTabbedPane2.addTab("Módulo 1", jScrollPane12);

        jTable17.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jTable17.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", null, null, null, null},
                {"02", null, null, null, null},
                {"03", null, null, null, null},
                {"04", null, null, null, null},
                {"05", null, null, null, null},
                {"06", null, null, null, null},
                {"07", null, null, null, null},
                {"08", null, null, null, null},
                {"09", null, null, null, null},
                {"10", null, null, null, null},
                {"11", null, null, null, null},
                {"12", null, null, null, null},
                {"13", null, null, null, null},
                {"14", null, null, null, null},
                {"15", null, null, null, null},
                {"16", null, null, null, null},
                {"17", null, null, null, null},
                {"18", null, null, null, null},
                {"19", null, null, null, null},
                {"20", null, null, null, null}
            },
            new String [] {
                "Nº ", "Aluno", "E-mail", "Cell", "Nota"
            }
        ));
        jTable17.setGridColor(new java.awt.Color(51, 51, 51));
        jTable17.setRowHeight(19);
        jScrollPane17.setViewportView(jTable17);

        jTabbedPane2.addTab("Módulo 2", jScrollPane17);

        jTable18.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jTable18.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", null, null, null, null},
                {"02", null, null, null, null},
                {"03", null, null, null, null},
                {"04", null, null, null, null},
                {"05", null, null, null, null},
                {"06", null, null, null, null},
                {"07", null, null, null, null},
                {"08", null, null, null, null},
                {"09", null, null, null, null},
                {"10", null, null, null, null},
                {"11", null, null, null, null},
                {"12", null, null, null, null},
                {"13", null, null, null, null},
                {"14", null, null, null, null},
                {"15", null, null, null, null},
                {"16", null, null, null, null},
                {"17", null, null, null, null},
                {"18", null, null, null, null},
                {"19", null, null, null, null},
                {"20", null, null, null, null}
            },
            new String [] {
                "Nº ", "Aluno", "E-mail", "Cell", "Nota"
            }
        ));
        jTable18.setGridColor(new java.awt.Color(51, 51, 51));
        jTable18.setRowHeight(19);
        jScrollPane18.setViewportView(jTable18);

        jTabbedPane2.addTab("Módulo 3", jScrollPane18);

        jTable19.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jTable19.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", null, null, null, null},
                {"02", null, null, null, null},
                {"03", null, null, null, null},
                {"04", null, null, null, null},
                {"05", null, null, null, null},
                {"06", null, null, null, null},
                {"07", null, null, null, null},
                {"08", null, null, null, null},
                {"09", null, null, null, null},
                {"10", null, null, null, null},
                {"11", null, null, null, null},
                {"12", null, null, null, null},
                {"13", null, null, null, null},
                {"14", null, null, null, null},
                {"15", null, null, null, null},
                {"16", null, null, null, null},
                {"17", null, null, null, null},
                {"18", null, null, null, null},
                {"19", null, null, null, null},
                {"20", null, null, null, null}
            },
            new String [] {
                "Nº ", "Aluno", "E-mail", "Cell", "Nota"
            }
        ));
        jTable19.setGridColor(new java.awt.Color(51, 51, 51));
        jTable19.setRowHeight(19);
        jScrollPane19.setViewportView(jTable19);

        jTabbedPane2.addTab("Módulo 4", jScrollPane19);

        jTable20.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jTable20.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", null, null, null, null},
                {"02", null, null, null, null},
                {"03", null, null, null, null},
                {"04", null, null, null, null},
                {"05", null, null, null, null},
                {"06", null, null, null, null},
                {"07", null, null, null, null},
                {"08", null, null, null, null},
                {"09", null, null, null, null},
                {"10", null, null, null, null},
                {"11", null, null, null, null},
                {"12", null, null, null, null},
                {"13", null, null, null, null},
                {"14", null, null, null, null},
                {"15", null, null, null, null},
                {"16", null, null, null, null},
                {"17", null, null, null, null},
                {"18", null, null, null, null},
                {"19", null, null, null, null},
                {"20", null, null, null, null}
            },
            new String [] {
                "Nº ", "Aluno", "E-mail", "Cell", "Nota"
            }
        ));
        jTable20.setGridColor(new java.awt.Color(51, 51, 51));
        jTable20.setRowHeight(19);
        jScrollPane20.setViewportView(jTable20);

        jTabbedPane2.addTab("Módulo 5", jScrollPane20);

        jTable21.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jTable21.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", null, null, null, null},
                {"02", null, null, null, null},
                {"03", null, null, null, null},
                {"04", null, null, null, null},
                {"05", null, null, null, null},
                {"06", null, null, null, null},
                {"07", null, null, null, null},
                {"08", null, null, null, null},
                {"09", null, null, null, null},
                {"10", null, null, null, null},
                {"11", null, null, null, null},
                {"12", null, null, null, null},
                {"13", null, null, null, null},
                {"14", null, null, null, null},
                {"15", null, null, null, null},
                {"16", null, null, null, null},
                {"17", null, null, null, null},
                {"18", null, null, null, null},
                {"19", null, null, null, null},
                {"20", null, null, null, null}
            },
            new String [] {
                "Nº ", "Aluno", "E-mail", "Cell", "Nota"
            }
        ));
        jTable21.setGridColor(new java.awt.Color(51, 51, 51));
        jTable21.setRowHeight(19);
        jScrollPane21.setViewportView(jTable21);

        jTabbedPane2.addTab("Módulo 6", jScrollPane21);

        jTabbedPane1.addTab("Alunos Mátriculados", jTabbedPane2);

        jComboBox1.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano 2019", "Ano 2020", "Ano 2021", "Ano 2022" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Buscar Ano");

        jButton2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuPrincipal MP = new MenuPrincipal();
        MP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable12;
    private javax.swing.JTable jTable17;
    private javax.swing.JTable jTable18;
    private javax.swing.JTable jTable19;
    private javax.swing.JTable jTable20;
    private javax.swing.JTable jTable21;
    // End of variables declaration//GEN-END:variables
}
